export const FETCH_USUARIO_REQUEST = 'FETCH_USUARIO_REQUEST'
export const FETCH_USUARIO_SUCCESS = 'FETCH_USUARIO_SUCCESS'
export const FETCH_USUARIO_ERROR = 'FETCH_USUARIO_ERROR'
export const FETCH_CLEAR_STATE = 'FETCH_CLEAR_STATE'
export const CLEAR_STATE = 'CLEAR_STATE'

export const FETCH_REGISTRO_SUCCESS = 'FETCH_REGISTRO_SUCCESS'
export const FETCH_REGISTRO_ERROR = 'FETCH_REGISTRO_ERROR'
export const CLEAR_REGISTRO = 'CLEAR_REGISTRO'

export const FETCH_REGISTROCATEGORIAS_SUCCESS = 'FETCH_REGISTROCATEGORIAS_SUCCESS'
export const FETCH_REGISTROCATEGORIAS_ERROR = 'FETCH_REGISTROCATEGORIAS_ERROR'

export const FETCH_REGISTROPUNTOS_SUCCESS = 'FETCH_REGISTROPUNTOS_SUCCESS'
export const FETCH_REGISTROPUNTOS_ERROR = 'FETCH_REGISTROPUNTOS_ERROR'

export const FETCH_REGISTROPRODUCTOS_SUCCESS = 'FETCH_REGISTROPRODUCTOS_SUCCESS'
export const FETCH_REGISTROPRODUCTOS_ERROR = 'FETCH_REGISTROPRODUCTOS_ERROR'

export const OPEN_MODAL= 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const VER_USUARIOS_SUCCESS= 'VER_USUARIOS_SUCCESS'


export const VER_CATEGORIAS_SUCCESS= 'VER_CATEGORIAS_SUCCESS'

export const VER_PRODUCTOS_SUCCESS= 'VER_PRODUCTOS_SUCCESS'

export const VER_PUNTOS_SUCCESS= 'VER_PUNTOS_SUCCESS'

export const VER_PROFILE_SUCCESS= 'VER_PROFILE_SUCCESS'

export const VER_PROFILE_ERROR = ' VER_PROFILE_ERROR'




